export const portfolioCopy = {
    es: {
        availability: 'Disponible para oportunidades',
        focus: 'Interfaces, datos y lo que los conecta.',
        intro: 'Desarrollo aplicaciones para negocios. Mi trabajo conecta interfaces claras con reglas de negocio, datos e integraciones que viven en el servidor.',
        projectLink: 'Explorar mi trabajo',
        architectureLabel: 'Esquema de arquitectura',
        architectureTitle: 'Una aplicación. Cada capa con su función.',
        ui: 'Interfaz',
        server: 'Servidor',
        data: 'Datos',
        uiDetail: 'Clientes · Pedidos · Pagos',
        serverDetail: 'Validación · Autorización · Reglas de negocio',
        dataDetail: 'Persistencia · Aislamiento por negocio',
        diagramCaption: 'Nodatix / CRM para negocios de repostería',
        caseLabel: '01 / PROYECTO EN FOCO',
        caseTitle: 'Nodatix',
        caseSubtitle: 'Un CRM para la operación de una repostería.',
        caseDescription: 'Clientes, pedidos, pagos y productos en una plataforma multiempresa. Cada negocio trabaja con su propia información.',
        roleLabel: 'MI PARTICIPACIÓN',
        role: 'Cofundador y desarrollador Full Stack',
        dates: 'ABR — AGO 2026',
        tabLabel: 'Explorar el proyecto Nodatix',
        tabs: ['Producto', 'Arquitectura', 'Mi aporte'],
        productTitle: 'De la gestión de clientes al seguimiento de pedidos.',
        productDescription: 'Módulos conectados para organizar la operación del negocio, con un dashboard y servicios de Supabase.',
        modules: [
            { title: 'Clientes y pedidos', detail: 'Organización de clientes y gestión de pedidos.' },
            { title: 'Productos y pagos', detail: 'Administración del catálogo y registro de pagos.' },
            { title: 'Dashboard operativo', detail: 'Un punto de consulta para la operación del negocio.' },
        ],
        architectureHeading: 'Separar responsabilidades para mantener el sistema.',
        architectureDescription: 'El backend se organiza en validaciones, repositorios y servicios. La validación y la autorización se mantienen del lado del servidor.',
        layers: [
            { title: 'Validación', tech: 'Zod', detail: 'Validación de datos de entrada.' },
            { title: 'Reglas de negocio', tech: 'Servicios', detail: 'Lógica del negocio separada de la interfaz.' },
            { title: 'Acceso a datos', tech: 'Prisma + PostgreSQL', detail: 'Persistencia y políticas RLS para aislar datos.' },
        ],
        contributionHeading: 'Decisiones que implementé.',
        contributions: [
            'Arquitectura multiempresa con aislamiento de información por negocio.',
            'Backend por capas con Zod, Prisma y Server Actions de Next.js.',
            'Integración con WhatsApp Cloud API: patrón outbox y validación HMAC-SHA256.',
            'Pruebas con Vitest sobre servicios, validaciones y reglas de negocio.',
        ],
        sourceNote: 'Vista técnica del proyecto. Las capturas de la aplicación se incorporarán cuando estén disponibles.',
        footer: 'Miguel Ángel Lázaro · Tehuacán, México',
        compare: 'Comparar con la versión actual',
    },
    en: {
        availability: 'Available for opportunities',
        focus: 'Interfaces, data and what connects them.',
        intro: 'I develop applications for businesses. My work connects clear interfaces with business rules, data and integrations that run on the server.',
        projectLink: 'Explore my work',
        architectureLabel: 'Architecture overview',
        architectureTitle: 'One application. A purpose for every layer.',
        ui: 'Interface',
        server: 'Server',
        data: 'Data',
        uiDetail: 'Customers · Orders · Payments',
        serverDetail: 'Validation · Authorization · Business rules',
        dataDetail: 'Persistence · Per-business isolation',
        diagramCaption: 'Nodatix / CRM for bakery businesses',
        caseLabel: '01 / PROJECT IN FOCUS',
        caseTitle: 'Nodatix',
        caseSubtitle: 'A CRM for bakery operations.',
        caseDescription: 'Customers, orders, payments and products in a multi-tenant platform. Each business works with its own information.',
        roleLabel: 'MY ROLE',
        role: 'Co-founder and Full Stack Developer',
        dates: 'APR — AUG 2026',
        tabLabel: 'Explore the Nodatix project',
        tabs: ['Product', 'Architecture', 'My contribution'],
        productTitle: 'From customer management to tracking orders.',
        productDescription: 'Connected modules for business operations, with a dashboard and Supabase services.',
        modules: [
            { title: 'Customers and orders', detail: 'Customer organization and order management.' },
            { title: 'Products and payments', detail: 'Catalog administration and payment records.' },
            { title: 'Operational dashboard', detail: 'A reference point for business operations.' },
        ],
        architectureHeading: 'Separate responsibilities to keep the system maintainable.',
        architectureDescription: 'The backend is organized into validation, repositories and services. Validation and authorization stay on the server.',
        layers: [
            { title: 'Validation', tech: 'Zod', detail: 'Validation of incoming data.' },
            { title: 'Business rules', tech: 'Services', detail: 'Business logic separated from the interface.' },
            { title: 'Data access', tech: 'Prisma + PostgreSQL', detail: 'Persistence and RLS policies for data isolation.' },
        ],
        contributionHeading: 'Decisions I implemented.',
        contributions: [
            'Multi-tenant architecture with per-business data isolation.',
            'Layered backend with Zod, Prisma and Next.js Server Actions.',
            'WhatsApp Cloud API integration: outbox pattern and HMAC-SHA256 validation.',
            'Vitest tests for services, validation and business rules.',
        ],
        sourceNote: 'Technical view of the project. Application screenshots will be added when available.',
        footer: 'Miguel Ángel Lázaro · Tehuacán, Mexico',
        compare: 'Compare with the current version',
    },
};
